### ISSUE TITLE
[Support] 电脑没有安装原神

### ISSUE THREAD

**Issue by tmdakm** [IceCreamTeamICT/LineLauncherCs#3]
### 简述需求

因为我电脑没有安装原神...

### 这是否是个重大问题而非诸如如何找到日志文件这种无意义问题？

- [X] 是的，这是个重大问题

**Comment by tmdakm** [comment]
@IloveEi 解决一下

**Comment by IloveEi** [comment]
1. 跳转到https://www.yuanshen.com/#/
2. 点击“进入官网”按钮。
3. 点击“游戏下载”，如果下载的文件的后缀为“.apk”则表明这是一个仅供安卓安卓的安装包；如果您是windows平台，后缀应为“.exe”，如果不是，请单击“其他下载”，选择您对应平台的安装包。
4. 下载后请点按“文件夹”图标打开文件所在文件夹（以微软边缘浏览器为例），右击，在菜单栏中单击“以管理员身份运行”，此期间务必确保您的网络流畅。
5. 启动器会默认安装在C盘，如果您的C盘空间吃紧，请将其放在其他盘符。
6. 跟随安装程序引导。
7. 在桌面找到启动器的快捷方式，双击打开。
8. 如有必要，更改游戏存档的路径，请确保您的盘符有150G以上的空间，否则下载程序将无法运行。
9. 等待启动器安装程序引导，当所有文件下载安装并校验完成后，即可点按“启动游戏”。
10. 如果有任何疑问，欢迎回到此页面再次问询我们的团队，届时，请务必提交您的错误截图。
